services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: moka
      POSTGRES_PASSWORD: moka
      POSTGRES_DB: moka
    volumes:
      - moka_pg:/var/lib/postgresql/data

volumes:
  moka_pg:
